version: "3.9"

services:
  ml-api:
    build: .
    container_name: ml-api-compose
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - ml-network

  redis:
    image: redis:7-alpine
    container_name: redis-service
    ports:
      - "6379:6379"
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge